<?php

return [
    'key' => 'slang.translates',
    'provider' => \Seiger\sLang\Tables\TranslatesTableData::class,
    'wire_target' => 'search,perPage,setSort,switchView,openCreateModal,closeModal,saveModal,runTableAction,updateInlineField,runInlineFieldAction,runHeaderAction,openDeleteModal,closeDeleteModal,deleteConfirmed,goToPage,firstPage,previousPage,nextPage,goLastPage',
    'per_page' => 10,
    'per_page_options' => [5, 10, 20, 30, 50, 100],
    'views' => ['table'],
    'default_view' => 'table',
    'default_sort' => 'key',
    'default_direction' => 'asc',
    'search' => [
        'enabled' => true,
        'state' => 'search',
        'width' => 'sm',
    ],
    'inline' => [
        'save_provider' => 'updateInlineField',
    ],
    'modal' => [
        'enabled' => true,
        'row_dblclick' => false,
        'title_create' => 'sLang::global.add_translation',
        'submit_label' => 'sLang::global.create_translation',
        'icon' => 'plus',
        'size' => 'md',
        'save_provider' => 'saveModal',
    ],
    'actions' => [
        [
            'key' => 'create',
            'type' => 'wire',
            'method' => 'openCreateModal',
            'icon' => 'plus',
            'label' => 'sLang::global.add_translation',
            'tone' => 'success',
            'icon_only' => true,
        ],
        [
            'key' => 'delete',
            'type' => 'wire',
            'method' => 'openDeleteModal',
            'icon' => 'trash',
            'label' => 'evo::global.action_delete',
            'tone' => 'danger',
            'icon_only' => true,
            'selection' => 'single',
        ],
        [
            'key' => 'synchronize',
            'type' => 'wire',
            'provider' => 'synchronizeTranslations',
            'icon' => 'refresh',
            'label' => 'sLang::global.synchronize',
            'attributes_provider' => 'synchronizeAttributes',
            'tone' => 'success',
            'variant' => 'filled',
            'placement' => 'controls',
        ],
    ],
    'columns' => [
        [
            'key' => 'key',
            'type' => 'text',
            'label' => 'KEY',
            'class' => 'evo-ui-table__title-column',
            'sortable' => true,
            'sort_field' => 'key',
            'editable' => false,
            'rules' => ['required', 'string', 'max:256'],
        ],
    ],
    'row_actions' => [
        [
            'key' => 'delete',
            'type' => 'wire',
            'method' => 'openDeleteModal',
            'argument' => 'id',
            'icon' => 'trash',
            'label' => 'evo::global.action_delete',
            'tone' => 'danger',
        ],
    ],
];
