<?php return [
/* ISO 3166-1 => ISO 639-1 */
    "AU" => "en",                       // The country: Австралия || Languages: английский
    "AT" => "de",                       // The country: Австрия || Languages: немецкий
    "AZ" => "az",                       // The country: Азербайджан || Languages: азербайджанский
    "AX" => "sq",                       // The country: Албания || Languages: албанский
    "AL" => "ar",                       // The country: Алжир || Languages: арабский
    "DZ" => "pl",                       // The country: Ангола || Languages: португальский
    "AI" => "ca",                       // The country: Андорра || Languages: каталанский
    "AO" => "en",                       // The country: Антигуа и Барбуда || Languages: английский
    "AD" => "es",                       // The country: Аргентина || Languages: испанский
    "AM" => "hy",                       // The country: Армения || Languages: армянский
    "AF" => "ps",                       // The country: Афганистан || Languages: пушту, дари
    "BS" => "en",                       // The country: Багамы || Languages: английский
    "BD" => "bn,en",                    // The country: Бангладеш || Languages: бенгальский, английский
    "BB" => "en",                       // The country: Барбадос || Languages: английский
    "BH" => "ar",                       // The country: Бахрейн || Languages: арабский
    "BY" => "be,ru",                    // The country: Беларусь || Languages: белорусский, русский
    "BZ" => "en",                       // The country: Белиз || Languages: английский
    "BE" => "fr,nl,de",                 // The country: Бельгия || Languages: французский, нидерландский, немецкий
    "BJ" => "fr",                       // The country: Бенин || Languages: французский
    "BG" => "bg",                       // The country: Болгария || Languages: болгарский
    "BO" => "es",                       // The country: Боливия || Languages: аймара, кечуа, испанский
    "BA" => "bs,sr,hr",                 // The country: Босния и Герцеговина || Languages: боснийский, сербский, хорватский
    "BW" => "en",                       // The country: Ботсвана || Languages: английский, сетсвана
    "BR" => "pt",                       // The country: Бразилия || Languages: португальский
    "BN" => "ms",                       // The country: Бруней || Languages: малайский
    "BF" => "fr",                       // The country: Буркина Фасо || Languages: французский
    "BI" => "fr",                       // The country: Бурунди || Languages: кирунди, французский
    "BT" => "dz",                       // The country: Бутан || Languages: дзонг-кэ (бхотия)
    "VU" => "en,fr,bi",                 // The country: Вануату || Languages: бислама, английский, французский
    "VA" => "it,la",                    // The country: Ватикан || Languages: латинский, итальянский
    "GB" => "en",                       // The country: Великобритания || Languages: английский
    "HU" => "hu",                       // The country: Венгрия || Languages: венгерский
    "VE" => "es",                       // The country: Венесуэла || Languages: испанский
    "TL" => "pt",                       // The country: Восточный Тимор || Languages: португальский, тетун
    "VN" => "vi",                       // The country: Вьетнам || Languages: вьетнамский
    "GA" => "rf",                       // The country: Габон || Languages: французский
    "HT" => "rf",                       // The country: Гаити || Languages: французский
    "GY" => "en",                       // The country: Гайана || Languages: английский
    "GM" => "en",                       // The country: Гамбия || Languages: английский
    "GH" => "en",                       // The country: Гана || Languages: английский
    "GT" => "es",                       // The country: Гватемала || Languages: испанский
    "GN" => "fr",                       // The country: Гвинея || Languages: французский
    "GW" => "pt",                       // The country: Гвинея-Бисау || Languages: португальский
    "DE" => "de",                       // The country: Германия || Languages: немецкий
    "HN" => "es",                       // The country: Гондурас || Languages: испанский
    "GD" => "en",                       // The country: Гренада || Languages: английский
    "GR" => "el",                       // The country: Греция || Languages: греческий
    "GE" => "ka",                       // The country: Грузия || Languages: грузинский
    "DK" => "da",                       // The country: Дания || Languages: датский
    "DJ" => "ar,fr",                    // The country: Джибути || Languages: арабский, французский
    "DM" => "en",                       // The country: Доминика || Languages: английский
    "DO" => "es",                       // The country: Доминиканская Республика || Languages: испанский
    "EG" => "ar",                       // The country: Египет || Languages: арабский
    "ZM" => "en",                       // The country: Замбия || Languages: английский
    "ZW" => "en",                       // The country: Зимбабве || Languages: английский
    "IL" => "he,ar",                    // The country: Израиль || Languages: иврит, арабский
    "IN" => "hi,en",                    // The country: Индия || Languages: хинди, английский
    "ID" => "ind",                      // The country: Индонезия || Languages: индонезийский
    "JO" => "ar",                       // The country: Иордания || Languages: арабский
    "IQ" => "ar,ku",                    // The country: Ирак || Languages: арабский, курдский
    "IR" => "fa",                       // The country: Иран || Languages: персидский
    "IE" => "ga,en",                    // The country: Ирландия || Languages: ирландский, английский
    "IS" => "is",                       // The country: Исландия || Languages: исландский
    "ES" => "es",                       // The country: Испания || Languages: испанский
    "IT" => "it ",                      // The country: Италия || Languages: итальянский
    "YE" => "ar",                       // The country: Йемен || Languages: арабский
    "CV" => "pt",                       // The country: Кабо-Верде || Languages: португальский
    "KZ" => "kk,ru",                    // The country: Казахстан || Languages: казахский, русский
    "KH" => "km",                       // The country: Камбоджа || Languages: кхмерский
    "CM" => "fr,en",                    // The country: Камерун || Languages: французский, английский
    "CA" => "en,fr",                    // The country: Канада || Languages: английский, французский
    "QA" => "ar",                       // The country: Катар || Languages: арабский
    "KE" => "sw,en",                    // The country: Кения || Languages: суахили, английский
    "CY" => "el,tr",                    // The country: Кипр || Languages: греческий, турецкий
    "KG" => "ky,en",                    // The country: Киргизия || Languages: киргизский, русский
    "KI" => "en",                       // The country: Кирибати || Languages: английский
    "CN" => "zh-hant,zh-hans",          // The country: Китай || Languages: китайский
    "CO" => "es",                       // The country: Колумбия || Languages: испанский
    "KM" => "fr,ar",                    // The country: Коморы || Languages: французский, арабский
    "CD" => "rf",                       // The country: Конго демократическая республика || Languages: французский
    "CG" => "rf",                       // The country: Конго республика || Languages: французский
    "CR" => "es",                       // The country: Коста-Рика || Languages: испанский
    "CI" => "rf",                       // The country: Кот-д’Ивуар || Languages: французский
    "CU" => "es",                       // The country: Куба || Languages: испанский
    "KW" => "ar",                       // The country: Кувейт || Languages: арабский
    "LA" => "lo",                       // The country: Лаос || Languages: лаосский
    "LV" => "lv",                       // The country: Латвия || Languages: латышский
    "LS" => "st,en",                    // The country: Лесото || Languages: сесото, английский
    "LR" => "en",                       // The country: Либерия || Languages: английский
    "LB" => "ar",                       // The country: Ливан || Languages: арабский
    "LY" => "ar",                       // The country: Ливия || Languages: арабский
    "LT" => "lt",                       // The country: Литва || Languages: литовский
    "LI" => "de",                       // The country: Лихтенштейн || Languages: немецкий
    "LU" => "de,fr",                    // The country: Люксембург || Languages: немецкий, французский, люксембургский диалект
    "MU" => "en",                       // The country: Маврикий || Languages: английский
    "MR" => "ar",                       // The country: Мавритания || Languages: арабский
    "MG" => "fr,mg",                    // The country: Мадагаскар || Languages: французский, малагасийский
    "MK" => "mk",                       // The country: Македония || Languages: македонский
    "MW" => "en,ny",                    // The country: Малави || Languages: английский, чичева
    "MY" => "ms",                       // The country: Малайзия || Languages: малазийский
    "ML" => "fr",                       // The country: Мали || Languages: французский
    "MV" => "dv",                       // The country: Мальдивы || Languages: мальдивский (дивехи)
    "MT" => "mt,en",                    // The country: Мальта || Languages: мальтийский, английский
    "MA" => "ar",                       // The country: Марокко || Languages: арабский
    "MH" => "en",                       // The country: Маршалловы Острова || Languages: английский
    "MX" => "es",                       // The country: Мексика || Languages: испанский
    "MZ" => "pt",                       // The country: Мозамбик || Languages: португальский
    "MD" => "md",                       // The country: Молдавия || Languages: молдавский
    "MC" => "fr",                       // The country: Монако || Languages: французский
    "MN" => "mn",                       // The country: Монголия || Languages: монгольский
    "MM" => "my",                       // The country: Мьянма || Languages: бирманский
    "NA" => "en",                       // The country: Намибия || Languages: английский
    "NR" => "na,en",                    // The country: Науру || Languages: науруанский, английский
    "NP" => "ne",                       // The country: Непал || Languages: непали
    "NE" => "fr",                       // The country: Нигер || Languages: французский
    "NG" => "en",                       // The country: Нигерия || Languages: английский
    "NL" => "nl",                       // The country: Нидерланды || Languages: нидерландский
    "NI" => "es",                       // The country: Никарагуа || Languages: испанский
    "NZ" => "en",                       // The country: Новая Зеландия || Languages: английский
    "NO" => "no",                       // The country: Норвегия || Languages: норвежский
    "AE" => "ar",                       // The country: Объединенные Арабские Эмираты || Languages: арабский
    "OM" => "ar",                       // The country: Оман || Languages: арабский
    "PK" => "en,ur",                    // The country: Пакистан || Languages: английский, урду
    "PW" => "en",                       // The country: Палау || Languages: английский
    "PA" => "es",                       // The country: Панама || Languages: испанский
    "PG" => "en",                       // The country: Папуа - Новая Гвинея || Languages: английский
    "PY" => "es,gn",                    // The country: Парагвай || Languages: испанский, гуарани
    "PE" => "ay,qu,es",                 // The country: Перу || Languages: аймара, кечуа, испанский
    "PL" => "pl",                       // The country: Польша || Languages: польский
    "PT" => "pt",                       // The country: Португалия || Languages: португальский
    "RU" => "ru",                       // The country: Россия || Languages: русский
    "RW" => "en,fr",                    // The country: Руанда || Languages: английский, французский, киньяруанда
    "RO" => "ro",                       // The country: Румыния || Languages: румынский
    "SV" => "es",                       // The country: Сальвадор || Languages: испанский
    "WS" => "sm,en",                    // The country: Самоа || Languages: самоанский, английский
    "SM" => "it",                       // The country: Сан-Марино || Languages: итальянский
    "ST" => "pt",                       // The country: Сан-Томе и Принсипи || Languages: португальский
    "SA" => "ar",                       // The country: Саудовская Аравия || Languages: арабский
    "SZ" => "en,ss",                    // The country: Свазиленд || Languages: английский, свази
    "KP" => "ko",                       // The country: Северная Корея || Languages: корейский
    "SC" => "fr,en",                    // The country: Сейшелы || Languages: креольский, французский, английский
    "SN" => "fr",                       // The country: Сенегал || Languages: французский
    "VC" => "en",                       // The country: Сент-Винсент и Гренадины || Languages: английский
    "KN" => "en",                       // The country: Сент-Китс и Невис || Languages: английский
    "LC" => "en",                       // The country: Сент-Люсия || Languages: английский
    "RS" => "sr",                       // The country: Сербия || Languages: сербский
    "SG" => "ms,en,zh-hant,zh-hans,ta", // The country: Сингапур || Languages: малайский, английский, китайский, тамильский
    "SY" => "ar",                       // The country: Сирия || Languages: арабский
    "SK" => "sk",                       // The country: Словакия || Languages: словацкий
    "SI" => "sl",                       // The country: Словения || Languages: словенский
    "US" => "en",                       // The country: Соединенные Штаты Америки || Languages: английский
    "SB" => "en",                       // The country: Соломоновы Острова || Languages: английский
    "SO" => "so,ar",                    // The country: Сомали || Languages: сомалийский, арабский
    "SD" => "ar",                       // The country: Судан || Languages: арабский
    "SR" => "nl",                       // The country: Суринам || Languages: нидерландский
    "SL" => "en",                       // The country: Сьерра-Леоне || Languages: английский
    "TJ" => "tg",                       // The country: Таджикистан || Languages: таджикский
    "TH" => "th",                       // The country: Таиланд || Languages: тайский
    "TZ" => "sw,en",                    // The country: Танзания || Languages: суахили, английский
    "TG" => "fr",                       // The country: Того || Languages: французский
    "TO" => "to,en",                    // The country: Тонга || Languages: тонганский, английский
    "TT" => "en",                       // The country: Тринидад и Тобаго || Languages: английский
    "TV" => "en",                       // The country: Тувалу || Languages: английский
    "TN" => "ar",                       // The country: Тунис || Languages: арабский
    "TM" => "tk",                       // The country: Туркмения || Languages: туркменский
    "TR" => "tr",                       // The country: Турция || Languages: турецкий
    "UG" => "en",                       // The country: Уганда || Languages: английский
    "UZ" => "uz",                       // The country: Узбекистан || Languages: узбекский
    "UA" => "uk",                       // The country: Украина || Languages: украинский
    "UY" => "es",                       // The country: Уругвай || Languages: испанский
    "FM" => "en",                       // The country: Федеративные штаты Микронезии || Languages: английский
    "FJ" => "en",                       // The country: Фиджи || Languages: английский
    "PH" => "tl,en",                    // The country: Филиппины || Languages: тагальский, английский
    "FI" => "fi,sv",                    // The country: Финляндия || Languages: финский, шведский
    "FR" => "rf",                       // The country: Франция || Languages: французский
    "HR" => "hr",                       // The country: Хорватия || Languages: хорватский
    "CF" => "fr,sg",                    // The country: Центрально-Африканская Республика || Languages: французский
    "TD" => "fr,ar",                    // The country: Чад || Languages: французский, арабский
    "ME" => "sr,sq",                    // The country: Черногория || Languages: сербский, албанский
    "CZ" => "cs",                       // The country: Чехия || Languages: чешский
    "CL" => "es",                       // The country: Чили || Languages: испанский
    "CH" => "fr,it,rm,de",              // The country: Швейцария || Languages: французский, итальянский, ретороманский, немецкий
    "SE" => "sv",                       // The country: Швеция || Languages: шведский
    "LK" => "si,ta",                    // The country: Шри-Ланка || Languages: сингальский, тамильский
    "EC" => "es",                       // The country: Эквадор || Languages: испанский
    "GQ" => "es,fr",                    // The country: Экваториальная Гвинея || Languages: испанский, французский
    "ER" => "ti,ar",                    // The country: Эритрея || Languages: тигринья, арабский
    "EE" => "et",                       // The country: Эстония || Languages: эстонский
    "ET" => "am",                       // The country: Эфиопия || Languages: амхарский
    "KR" => "ko",                       // The country: Южная Корея || Languages: корейский
    "ZA" => "en,af",                    // The country: Южно-Африканская Республика || Languages: английский, африкаанс
    "JM" => "en",                       // The country: Ямайка || Languages: английский
    "JP" => "ja"                        // The country: Япония || Languages: японский
];
