<?php
/**
 * Список мов для мультимовності
 */
return [
    'en' => ['name' => 'English',       'short' => 'Eng',      'ISO 639-1' => 'en', 'ISO 639-3' => 'eng',   'country' => 'English'],
    'uk' => ['name' => 'Українська',    'short' => 'Укр',      'ISO 639-1' => 'uk', 'ISO 639-3' => 'ukr',   'country' => 'Ukraine'],
    'ab' => ['name' => 'Абхазский',     'short' => 'Абх',      'ISO 639-1' => 'ab', 'ISO 639-3' => 'abk',   'country' => 'Abkhazia'],
    'az' => ['name' => 'Azərbaycanca',  'short' => 'Azərb',    'ISO 639-1' => 'az', 'ISO 639-3' => 'aze',   'country' => 'Azerbaijan'],
    'bg' => ['name' => 'Български',     'short' => 'Бъл',      'ISO 639-1' => 'bg', 'ISO 639-3' => 'bul',   'country' => 'Bulgaria'],
    'hu' => ['name' => 'Magyar',        'short' => 'Mag',      'ISO 639-1' => 'hu', 'ISO 639-3' => 'hun',   'country' => 'Hungary'],
    'nl' => ['name' => 'Nederlands',    'short' => 'Ned',      'ISO 639-1' => 'nl', 'ISO 639-3' => 'nld',   'country' => 'Netherlands'],
    'el' => ['name' => 'Ελληνικά',      'short' => 'Ελληνικά', 'ISO 639-1' => 'el', 'ISO 639-3' => 'ell',   'country' => 'Greece'],
    'da' => ['name' => 'Dansk',         'short' => 'Dan',      'ISO 639-1' => 'da', 'ISO 639-3' => 'dan',   'country' => 'Denmark'],
    'ga' => ['name' => 'Gaeilge',       'short' => 'Gae',      'ISO 639-1' => 'ga', 'ISO 639-3' => 'gle',   'country' => ''],
    'is' => ['name' => 'Íslenska',      'short' => 'Ísl',      'ISO 639-1' => 'is', 'ISO 639-3' => 'isl',   'country' => ''],
    'es' => ['name' => 'Español',       'short' => 'Esp',      'ISO 639-1' => 'es', 'ISO 639-3' => 'spa',   'country' => 'Spain'],
    'it' => ['name' => 'Italiano',      'short' => 'Ital',     'ISO 639-1' => 'it', 'ISO 639-3' => 'ita',   'country' => 'Italy'],
    'lv' => ['name' => 'Latviešu',      'short' => 'Latv',     'ISO 639-1' => 'lv', 'ISO 639-3' => 'lav',   'country' => ''],
    'lt' => ['name' => 'Lietuvių',      'short' => 'Liet',     'ISO 639-1' => 'lt', 'ISO 639-3' => 'lit',   'country' => ''],
    'de' => ['name' => 'Deutsch',       'short' => 'Deut',     'ISO 639-1' => 'de', 'ISO 639-3' => 'deu',   'country' => 'Germany'],
    'no' => ['name' => 'Norsk',         'short' => 'Norsk',    'ISO 639-1' => 'no', 'ISO 639-3' => 'nor',   'country' => 'Norway'],
    'pl' => ['name' => 'Polski',        'short' => 'Pols',     'ISO 639-1' => 'pl', 'ISO 639-3' => 'pol',   'country' => 'Poland'],
    'pt' => ['name' => 'Português',     'short' => 'Port',     'ISO 639-1' => 'pt', 'ISO 639-3' => 'por',   'country' => ''],
    'pt-br' => ['name' => 'Português BR','short' => 'Port BR',  'ISO 639-1' => 'pt-br', 'ISO 639-3' => 'pt-BR',   'country' => 'Brazil'],
    'ro' => ['name' => 'Română',        'short' => 'Rom',      'ISO 639-1' => 'ro', 'ISO 639-3' => 'ron',   'country' => 'Romania'],
    'sr' => ['name' => 'Srpski',        'short' => 'Srp',      'ISO 639-1' => 'sr', 'ISO 639-3' => 'srp',   'country' => ''],
    'sk' => ['name' => 'Slovenčina',    'short' => 'Slovenč',  'ISO 639-1' => 'sk', 'ISO 639-3' => 'slk',   'country' => ''],
    'sl' => ['name' => 'Slovenščina',   'short' => 'Slovenš',  'ISO 639-1' => 'sl', 'ISO 639-3' => 'slv',   'country' => ''],
    'fr' => ['name' => 'Français',      'short' => 'Fran',     'ISO 639-1' => 'fr', 'ISO 639-3' => 'fra',   'country' => 'French'],
    'hr' => ['name' => 'Hrvatski',      'short' => 'Hrv',      'ISO 639-1' => 'hr', 'ISO 639-3' => 'hrv',   'country' => ''],
    'cs' => ['name' => 'Čeština',       'short' => 'Češt',     'ISO 639-1' => 'cs', 'ISO 639-3' => 'ces',   'country' => 'Czech Republic'],
    'sv' => ['name' => 'Svenska',       'short' => 'Sven',     'ISO 639-1' => 'sv', 'ISO 639-3' => 'swe',   'country' => 'Sweden'],
    'et' => ['name' => 'Eesti',         'short' => 'Eest',     'ISO 639-1' => 'et', 'ISO 639-3' => 'est',   'country' => 'Estonia'],
    'uz' => ['name' => 'Ўзбек',         'short' => 'Ўзбек',    'ISO 639-1' => 'uz', 'ISO 639-3' => 'uzb',   'country' => ''],
    'ja' => ['name' => '日本語',         'short' => '日本語',    'ISO 639-1' => 'ja', 'ISO 639-3' => 'jpn',   'country' => 'Japan'],
    'zh-hant' => ['name' => '繁體中文',  'short' => '繁體中文',   'ISO 639-1' => 'zh-TW', 'ISO 639-3' => 'zh-TW',   'country' => 'Chinese (Traditional)'],
    'zh-hans' => ['name' => '简体中文',  'short' => '简体中文',   'ISO 639-1' => 'zh-CN', 'ISO 639-3' => 'zh-CN',   'country' => 'Chinese (Simplified)'],
    'th' => ['name' => 'ไทย',           'short' => 'ไทย',      'ISO 639-1' => 'th', 'ISO 639-3' => 'tha',   'country' => 'Thailand'],
    'vi' => ['name' => 'Tiếng Việt',    'short' => 'Tiếng Việt','ISO 639-1' => 'vi', 'ISO 639-3' => 'vie',   'country' => 'Vietnam'],
    'sg' => ['name' => 'yângâ tî sängö','short' => 'yângâ tî sängö','ISO 639-1' => 'sg', 'ISO 639-3' => 'sag',   'country' => 'Singapore'],
    'tr' => ['name' => 'Türkçe',        'short' => 'Türkçe',   'ISO 639-1' => 'tr', 'ISO 639-3' => 'tur',   'country' => 'Turkish'],
    'fi' => ['name' => 'suomi',         'short' => 'suomi',    'ISO 639-1' => 'fi', 'ISO 639-3' => 'fin',   'country' => 'Finland'],
    'km' => ['name' => 'ខ្មែរ, ខេមរភាសា, ភាសាខ្មែរ','short' => 'ខ្មែរ, ខេមរភាសា, ភាសាខ្មែរ',  'ISO 639-1' => 'km', 'ISO 639-3' => 'khm', 'country' => 'Cambodia'],
    'ko' => ['name' => '한국어',         'short' => '한국어',    'ISO 639-1' => 'ko', 'ISO 639-3' => 'kor',   'country' => 'South Korea'],
    'id' => ['name' => 'Bahasa Indonesia','short' => 'Bahasa', 'ISO 639-1' => 'id', 'ISO 639-3' => 'ind',   'country' => 'Indonesia'],
    'ms' => ['name' => 'Melayu',        'short' => 'Melayu',   'ISO 639-1' => 'ms', 'ISO 639-3' => 'msa',   'country' => 'Malaysia'],
    'hi' => ['name' => 'हिन्दी',           'short' => 'हिन्दी',     'ISO 639-1' => 'hi', 'ISO 639-3' => 'hin',   'country' => 'India'],
    'be' => ['name' => 'Беларуская',    'short' => 'Бел',      'ISO 639-1' => 'be', 'ISO 639-3' => 'bel',   'country' => 'Belarus'],
    'ru' => ['name' => 'Русский',       'short' => 'Рус',      'ISO 639-1' => 'ru', 'ISO 639-3' => 'rus',   'country' => 'Russia'],
];